### ISSUE TITLE
Remove global dependency to window and document

### ISSUE THREAD

**Issue by vizath** [hammerjs/hammer.js#849] opened 2015-09-02 21:39 UTC
Currently, Hammejs is required to have a DOM available. This makes non-browser tests breaks with the error 
```
})(window, document, 'Hammer');
   ^
ReferenceError: window is not defined
```

Here, this test would fail:
```
// test.js
require('hammerjs');
```
`mocha test.js`

This makes testing components that `require` Hammer to fail.
Is there a way to differ the window binding ?

https://github.com/hammerjs/hammer.js/issues/178 may have the same issue.

**Comment by vizath** [comment] 2015-09-02 22:07
My work-around, since I do not use Hammerjs in my tests (yet):
```
// hammerWrapper.js
var implementation = function() {};
if (typeof module === 'undefined') {
	implementation = require('hammerjs');
}
module.exports = implementation;
```
```
// test.js
require('./hammerWrapper.js');
```
`mocha test.js`

Looking forward to test Hammerjs by providing custom window objects in the future.

**Comment by runspired** [comment] 2015-11-11 15:20
Curious, what non-browser test environment are you using?  If it's Phantom, you should have `window` available to you.

Closing in favor of more discussion here: https://github.com/hammerjs/hammer.js/pull/598
And as a duplicate of https://github.com/hammerjs/hammer.js/issues/597

**Closed by runspired** 2015-11-11 15:20 UTC

**Comment by vizath** [comment] 2015-11-11 22:01
Thanks for the heads up.
We are testing in a non-browser environment, using jsdom.
There was a problem requiring hammer since it expects to have the window object in the global scope.

Thanks.
