### ISSUE TITLE
TUIO Board Game Sample ?

### ISSUE THREAD

**Issue by JpEncausse** [hammerjs/hammer.js#500] opened 2014-03-12 21:44 UTC
Hi,

I saw CaressJS provides a plugin for HammerJS. I'd like to know if there is demo or library using HammerJS to handle TableTop or BoardGame

- Handling touch generated by objet
- Ignoring "old" touch (to bypass limit of 12 touches)

**Comment by arschmitz** [comment] 2015-06-08 22:59
Closing this as not a bug

**Closed by arschmitz** 2015-06-08 22:59 UTC
