### ISSUE TITLE
I use hammer.js on a custombox, it doesn't work

### ISSUE THREAD

**Issue by linuxjcq** [hammerjs/hammer.js#671] opened 2014-09-21 07:14 UTC
Hi, 

    I use http://dixso.github.io/custombox/ as modal for popup a window, I bind hammer touch event to the custombox, the hammer's touch event doesn't work, please help.

Thanks!

**Comment by runspired** [comment] 2015-08-07 17:47
Closing as not a bug.

**Closed by runspired** 2015-08-07 17:47 UTC
