### ISSUE TITLE
Add own recognizers

### ISSUE THREAD

**Issue by nexflo** [hammerjs/hammer.js#920] opened 2016-02-13 11:42 UTC
Whats the cleanest way of adding own recognizers like drawing a triangle, or a square?

**Comment by arschmitz** [comment] 2016-02-20 13:42
please see the api docs under recognizers for the add method http://hammerjs.github.io/api/#hammer.recognizer closing this since its not a bug for support please try our slack or StackOverflow

**Closed by arschmitz** 2016-02-20 13:42 UTC
