### ISSUE TITLE
How to prevent browsers default behavior?

### ISSUE THREAD

**Issue by josdejong** [hammerjs/hammer.js#781] opened 2015-04-14 09:44 UTC
When using a pan gesture, I saw that on Firefox the default browser behavior is not prevented. I create a Hammer instance like:

```js
    var child = document.getElementById('child');
    var hammer2 = new Hammer(child)
        .on('pan', function (event) {
          event.preventDefault(); // how to preventDefault? Not working on Firefox
        });
```

Now, when I drag the child element, text inside the element and surrounding it will be selected when running on Firefox 37. Works fine on Chrome. 

Here is a jsbin to demonstrate the issue: http://jsbin.com/begoco/5/edit?html,output

The example [on the website](http://hammerjs.github.io/) *does* work fine on Firefox, it does not select any text, so I may be overlooking something?

**Comment by arschmitz** [comment] 2015-06-07 19:30
@josdejong use css `pointer-events` to prevent highlighting and things like that. I'm going to close this as not a bug

**Closed by arschmitz** 2015-06-07 19:30 UTC

**Comment by josdejong** [comment] 2015-06-08 07:33
ah, of course. Good point, thanks.
