### ISSUE TITLE
Pan events not firing on straight vertical pan

### ISSUE THREAD

**Issue by gingerchris** [hammerjs/hammer.js#1003] opened 2016-07-26 16:05 UTC
I'm experiencing a strange issue where pan events (panstart, pan, panend) are not firing, but only when the cursor is dragged vertically up or down in a straight line.  The events fire ok if the drag deviates from that line, or if the cursor is dragged horizontally.

There's a reproduction of the issue here - http://codepen.io/gingerchris/pen/BzVojW

Using hammer 2.0.8.
I've tested in up-to-date versions of Safari, Chrome and Firefox, all on OSX 10.11.5 and with both a trackpad and mouse

**Comment by gingerchris** [comment] 2016-07-26 16:25
Just discovered that explicitly setting `direction: DIRECTION_ALL` fixes this issue. 
The default direction appears to be set to `DIRECTION_HORIZONTAL` but the docs suggest it should be `DIRECTION_ALL`.

See http://codepen.io/gingerchris/pen/PzaPRK

**Comment by arschmitz** [comment] 2016-07-26 19:48
The default is `horizontal` because `all` prevents scrolling and so is not a good default value. To receive vertical pan you need to set `all`. Closing as this is not a bug.

**Closed by arschmitz** 2016-07-26 19:48 UTC
