### ISSUE TITLE
pinch/rotate velocity

### ISSUE THREAD

**Issue by sebakerckhof** [hammerjs/hammer.js#752] opened 2015-01-23 07:16 UTC
Hey,

Thanks for this great library. However, is there a way to get rotate and pinch velocity or is this limited to drag velocity? In case of the last, is there a particular reason why this is hard to add and if not can you direct me to the right place in the code to add this? Thanks!

**Comment by mkv123** [comment] 2015-04-07 06:20
Duplicate of #595

**Comment by runspired** [comment] 2015-08-07 16:35
Closing in favor of the previous ticket.

**Closed by runspired** 2015-08-07 16:35 UTC
