### ISSUE TITLE
Late binding with Hammer

### ISSUE THREAD

**Issue by braco** [hammerjs/hammer.js#831] opened 2015-07-24 22:09 UTC
Because I have a huge list of DOM elements that need binding, I would like to use an external onTouchStart event before binding Hammer.

Something like this: <... onTouchStart='userTouched' />

```
var userTouched = function(event) {
    // var hammer = setup hammer
}
```

But this for this to work, it would require passing the previous touch event to Hammer:
```
var userTouched = function(event) {
    // var hammer = setup hammer
   hammer.trigger(DOM, event);
}
```

Is triggering like that possible? Nothing I'm trying with emit or trigger seems to work.

**Comment by runspired** [comment] 2015-07-28 15:18
@braco while that's not possible, what you might want to do instead is delegate gestures detected from a single hammer instance using the base element of your list.

**Comment by runspired** [comment] 2015-08-07 16:56
Closing as this is an implementation question, not a bug report.

**Closed by runspired** 2015-08-07 16:56 UTC
