### ISSUE TITLE
Double event issue with hybrid mouse/touch system

### ISSUE THREAD

**Issue by Moeriki** [hammerjs/hammer.js#447] opened 2014-01-20 10:48 UTC
Dear all,

I'm writing software for a multitouch board. I have an issue with double events.

The demo below is tested on Chrome 32, Firefox 26 and Safari 7.0.1 on OS X.

I have the following log line in my main file.
```javascript
Hammer(document).on('tap doubletap', function(e) {
  console.log('Hammer ' + e.type);
});
```

I put the following log *(in hammer.js)* right before checking all the gestures.
```javascript
console.log('check all gestures for ' + eventData.srcEvent.type + '/' + eventData.eventType);
Hammer.utils.each(this.gestures, function(gesture) {
  // …
});
```

This is my console output on a **single tap**.
```
check all gestures for touchstart/start (hammer.js:833)
check all gestures for touchend/end (hammer.js:833)
Hammer tap
check all gestures for mousedown/start (hammer.js:833)
check all gestures for mouseup/end (hammer.js:833)
Hammer doubletap
Hammer tap
```

As you can obviously see my system triggers mouse events (for the first touch), as well as touch events for all touches.

Has anyone had this problem, and is there a known solution for this? As for now I'll continue debugging and trying out solutions.

**Sidenote:** I can't disable mouse events. The board I develop for is connected to a desktop computer. Thus the application should be usable via mouse on desktop, as well as via touch on the board.

Thanks for reading.

**Comment by emin93** [comment] 2015-03-13 08:31
Same problem here, getting the event twice on a single tap.

**Comment by arschmitz** [comment] 2015-06-08 05:16
Closing this a duplicate of #292

**Closed by arschmitz** 2015-06-08 05:16 UTC
