### ISSUE TITLE
Is it bad practice to use hammer on a global element such as body?

### ISSUE THREAD

**Issue by charandas** [hammerjs/hammer.js#861] opened 2015-10-26 21:18 UTC
I was going to ask in SO but thought this might be pertinent for new users to hammer.

On this [html5rocks](http://www.html5rocks.com/en/mobile/touchandmouse/) article in section 6 - <em>Keep Touch Handlers Contained, or They’ll Jank Your Scroll</em>, it is recommended to use touch handlers on restricted parts of the page, for example, it says not to have touch handlers be registered on `<body>`.

I have been doing this in a production app, just so these touch gestures don't impact my app.

    var hammerTime, hammerDisableEvent, events = 'transform dragleft dragright swipe swipeleft swiperight';
    hammerTime = new Hammer($('body').get(0));

    hammerTime.on(events, function(ev){
        ev.preventDefault();
    });

Is this a bad practice?

**Comment by arschmitz** [comment] 2015-10-27 00:43
@charandas the issue tracker is for bugs for support please try SO or Slack channel. Closing this as not a bug

**Closed by arschmitz** 2015-10-27 00:43 UTC
