### ISSUE TITLE
press disable drag?

### ISSUE THREAD

**Issue by cescoferraro** [hammerjs/hammer.js#972] opened 2016-05-04 13:56 UTC
I want to use the press event on my app, but then I cant drag/scroll down the page if I happen to hit the photos expecting a press event. Is this the expected behavior? Am I missing something?

**Comment by arschmitz** [comment] 2016-05-04 14:10
With out a test case its hard to say much but it sounds like you are using something thats setting touch-action value to none. press only needs manipulation. what other hammer events are you using?

**Comment by cescoferraro** [comment] 2016-05-05 13:46
@arschmitz i will come up with a plunkr trying to replicate this issue. Its worth saying that I am on a Ionic2 platform.

**Comment by cescoferraro** [comment] 2016-05-05 17:58
@arschmitz there is no need. You can check my issue at http://hammerjs.github.io/.

Interestingly it does not happen on the press event, but you can check it on the Rotate and Pinch/Zoom examples. You cannot scroll down the when hitting them, which its a bummer on a photo based website.
Tested on iPhone 6 and iPhone6 plus

**Comment by arschmitz** [comment] 2016-05-05 19:29
@cescoferraro thats exactly what i was talking about it should not scroll on those examples. please see http://hammerjs.github.io/touch-action/ and https://www.w3.org/TR/pointerevents/#the-touch-action-css-property 

Closing as not a bug.

**Closed by arschmitz** 2016-05-05 19:29 UTC

**Comment by cescoferraro** [comment] 2016-05-05 20:09
@arschmitz is there a workaround this? setting the element touch-action to manipulation does not solve the issue

**Comment by arschmitz** [comment] 2016-05-05 20:42
@cescoferraro are you setting the css touch action or doing it in your hammer instance the css is not supported in many browsers you must set it in your hammer instance like in the docs page i linked

**Comment by cescoferraro** [comment] 2016-05-05 20:55
i am setting the css.
I am not creating a Hammer instance. I am just using the event as an ANgular2 event like

```
<img  template="ngFor #item of allPhotosTWO " src="{{item.url}}" (press)="photoswipe()" alt="">
```

**Comment by arschmitz** [comment] 2016-05-05 20:56
@cescoferraro im not an angular user but basicly the default hammer setup wont work you need to customize the hammer instance the css won't be enough.

**Comment by cescoferraro** [comment] 2016-05-05 21:15
i will try to create a component that initialize Hammer on its own initialization.
Would that be it?
```
var hammertime = Hammer(element).on("press", function(event) {
        alert('hello!');
    })
hammertime.({ cssProps: {touch-action: manipulation} });
```

**Comment by cescoferraro** [comment] 2016-05-05 22:11
the new component solved the issue right away!
thanks for your time @arschmitz 
hammer rocks

**Comment by arschmitz** [comment] 2016-05-06 16:36
@cescoferraro awesome glad you like!
