### ISSUE TITLE
Dragging is not working on v2.0.4

### ISSUE THREAD

**Issue by rukbin011** [hammerjs/hammer.js#778] opened 2015-03-31 01:48 UTC
I'm new to hammer, I tried using the drag event and its not working, is the drag event is still working in the latest varsion?

**Comment by enrichit** [comment] 2015-03-31 10:11
There is no "drag" event in Hammer.js as I belive that would conflict with the native [drag and drop](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Drag_and_drop) API, which is nothing to do with handling touch events.

There is however, a "pan" event and a "swipe" event. You can see that working below.

![capture](https://cloud.githubusercontent.com/assets/3854592/6916655/f85c458a-d795-11e4-84ff-9a0fe9c0ff2a.png)

**Comment by pankaj-arunsingh** [comment] 2015-05-18 02:24
In hammer js v1.1 there were gesture events for drag, dragstart, dragend, dragup, dragdown, dragleft, dragright. Can anyone guide as to how to use these drag events in latest version of hammer js. How are these events replaced in latest version. If anyone tried please help. Thanks in advance. :-)

**Comment by arschmitz** [comment] 2015-06-07 19:36
I'm going to close this since its not a bug but rather was removed in v2

**Closed by arschmitz** 2015-06-07 19:36 UTC
