### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by Prinzhorn** [hammerjs/hammer.js#407] opened 2013-12-10 11:22 UTC
I just wanted to create a test for #406 in order to fix it but I don't quite understand the test suite.

Is my observation correct that the only thing you are currently testing is that for each gesture the correct events fire with parameters of correct type? Aren't there any tests for all the options, e.g. `tap_max_distance`, `drag`, `doubletap_interval` and so on?

**Comment by arschmitz** [comment] 2015-06-08 22:50
Closing this as old and not a bug we are working on improving test coverage and get automated cross browser testing set up

**Closed by arschmitz** 2015-06-08 22:50 UTC
