### ISSUE TITLE
How to hide the div when you drag it with the hammer.js in the right and to the bottom?

### ISSUE THREAD

**Issue by NekoStudio** [hammerjs/hammer.js#931] opened 2016-03-02 18:23 UTC
There div dragging it implemented by hammer.js and velotsity.sj. The question is, how do I make the div when you drag it to the bottom or right of hiding and did not return to the starting position.

```
var box = document.getElementById("box");
var $box = $("#box");
var hammer = new Hammer(box);
hammer.add(new Hammer.Pan({ threshold: 0, pointers: 0 }));

hammer.on('panmove', function(event) {
    $.Velocity.hook($box, 'translateX', event.deltaX + 'px');
    $.Velocity.hook($box, 'translateY', event.deltaY + 'px');
     $.Velocity.hook($box, 'translateZ', '0');
});

hammer.on('panend', function(event) {
    $("#box").velocity({translateX: [0,event.deltaX], translateY: [0,event.deltaY]});
});
```

```
#box_wrap {
    width:100%;
    height:600px;
    background-color:green;
}
#box {
    width:250px;
    height:250px;
    background-color:red;
}
```

```
<div id="box_wrap">
  <div id="box">
  </div>
</div>
```

Example: http://jsfiddle.net/Jegerkun/nu81y2Lu/4/

Here, then what I am saying
https://dribbble.com/shots/2371725-Screen-transitions-feed-to-details-and-back

Thanks in advance and sorry for my english

**Comment by Mourtz** [comment] 2016-03-03 21:29
@NekoStudio  If I got it right you want an effect like this.

Example: http://jsfiddle.net/bst8rnqm/

Hope this helped you get it done.

**Comment by NekoStudio** [comment] 2016-03-03 23:06
Thank you, but it's not. I was referring to, a red square, when you pull it to the left or to the right, he vanished at all, and was returning not to the place. About the I'm talking about here https://dribbble.com/shots/2371725-Screen-transitions-feed-to-details-and-back

**Comment by NekoStudio** [comment] 2016-03-03 23:06
Thank you, but it's not. I was referring to, a red square, when you pull it to the left or to the right, he vanished at all, and was returning not to the place. About the I'm talking about here https://dribbble.com/shots/2371725-Screen-transitions-feed-to-details-and-back

**Comment by NekoStudio** [comment] 2016-03-03 23:07
Thank you, but it's not. I was referring to, a red square, when you pull it to the left or to the right, he vanished at all, and was returning not to the place. About the I'm talking about here https://dribbble.com/shots/2371725-Screen-transitions-feed-to-details-and-back

**Comment by Mourtz** [comment] 2016-03-04 01:12
[Here](http://jsfiddle.net/n9ukgwou/) are exactly the same transition effects shown in the gif you sent.

Btw, I dont think there was any reason to create an issue for this. Your problem with div returing to the starting position was caused by velocity.js instead of hammer.js .

**Comment by arschmitz** [comment] 2016-03-04 02:28
Im going to close this since its not a bug and more of a question but feel free to continue discussing it in this issue

**Closed** 2016-07-01 06:25 UTC
