### ISSUE TITLE
pan: (x, y) change since last event

### ISSUE THREAD

**Issue by davidfig** [hammerjs/hammer.js#786] opened 2015-04-20 04:25 UTC
I was looking for the amount of panning that happened since the last event fired. I couldn't figure out how to do it with the current API set, so I added a new variable to the event object:

function computeDeltaXY(session, input) {
...
    input.deltaXEvent = (center.x - (prevInput.center ? prevInput.center.x : 0));
    input.deltaYEvent = (center.y - (prevInput.center ? prevInput.center.y : 0));
}

Let me know if there's a better way to do this.

**Comment by arschmitz** [comment] 2015-06-07 19:28
@davidfig why are you not just using a closure and storing the previous  cords in a variable. Then checking it in then check in the next event? I'm going to close this as not a bug.

**Closed by arschmitz** 2015-06-07 19:28 UTC

**Comment by davidfig** [comment] 2015-06-15 03:09
My thinking was that this seemed an interesting piece of data that the library could handle instead of the app, since it had little overhead and was helpful in a few scenarios. But I understand if that's not the case. Thanks for checking back.
