### ISSUE TITLE
Double tap causes image to flip at random orientation 

### ISSUE THREAD

**Issue by suchg** [hammerjs/hammer.js#913] opened 2016-01-28 16:09 UTC
Touching the image with two figures results in the image changing its orientation to a seemingly random angle.
Ideally there should be no change in the image on normal tap.

**Comment by runspired** [comment] 2016-01-28 17:12
Closing as not a bug.  If you are referring to the demo, there is a rotation handler defined but there is no two fingered tap defined.  With a rotation handler, if you lift your fingers in the opposite order as you set them down, you will cause a 180 degree rotation.  There is an outstanding feature improvement idea here for allowing you to shift the tracking finger, but this is something also easily implemented in your own handler logic.  Each touch has a unique tracking ID.

**Closed by runspired** 2016-01-28 17:12 UTC
