### ISSUE TITLE
[Accessibility] - 'Tap' does not fire when clicked

### ISSUE THREAD

**Issue by leifdejong** [hammerjs/hammer.js#803] opened 2015-06-08 18:36 UTC
In Voice Over (VO) on iOS devices, 'Tap' is never fired. 

Replication: 
1. Bind an element to 'tap'
2. Turn on Voice Over
3. Double tap to 'click'

Expected: 
1. Event handler should fire

VO does a click and somewhere, that event gets lost in Hammer. The workaround was to bind both events (click, tap) and then throw 'click' away if 'tap' is recognized. If tap is not found, it goes ahead and fires the click event. 

Solution: 

My recommendation for Hammer would be to bind the `click` when the 'tap' is bound and do some checks internally. This is the only way as we can know when voiceover is being used. Will be working on a fix.

**Comment by arschmitz** [comment] 2015-06-08 18:48
@leifdejong Thank you for reporting this i will look into this.

Im a little on sure on what the semantics should be here though as tap and click are different this is equivalent in some ways to expecting tap to fire if a jQuery plugin did `.trigger( "click" )` or even a native `.click()` this would never cause a tap event. There are many situations where a click can happen with out an accompanying up / down events is it expected behavior that all of these should trigger a simulated tap event?

 I'm interested to hear what others think about this? @jtangelder

**Comment by leifdejong** [comment] 2015-06-08 18:56
Yap. Had a similar issue when binding 'tap' to an element in a UI plugin and then having a MVC* framework (in our case Backbone) bind a click on that same element, the click is never picked up. Thats why I think that the click even should always be triggered in some controlled way.

This was my hack. Its ugly!

```javascript
var $el = $('body');
$el.on('tap click', eventHandler.bind(this));

function eventHandler(event) {
  if (event.isFinal) {
    action();
    event.stopImmediatePropagation();
    event.preventDefault();
  } else {
    action();
  }
} 
```

**Comment by arschmitz** [comment] 2015-06-08 21:14
@leifdejong so we have been discussing this on slack and we definitely want to try to tackle this problem as it 100% is a real problem. On jQuery mobile we have had multiple similar issues filed with out own tap event. 

What we are not sure is if we should fix this in hammer proper or take a more modular approach and just provide the needed hooks and develop an add on module to handle this.

**Comment by leifdejong** [comment] 2015-06-09 03:24
@arschmitz any way that I can be involved? I can devote some time to hacking something up.

**Comment by arschmitz** [comment] 2015-06-09 03:26
@leifdejong absolutely we are looking for team members see https://github.com/hammerjs/hammer.js/issues/800 and join us on slack at http://hammerjs-slackin.herokuapp.com/

**Comment by runspired** [comment] 2015-06-17 01:36
@arschmitz this issue is another manifestation of the breakdown of `tap` vs `click`.  Since these sorts of clicks never fire pointer events at all, `tap` handlers don't execute.

It's a driving motivation behind the new approach here: https://github.com/runspired/ember-mobiletouch/issues/56

Do you know if PEP handles these sorts of cases?

**Comment by arschmitz** [comment] 2015-06-17 01:38
this is the same thing as #808 closing in favor of that this is another tap as a fast click issue

**Closed by arschmitz** 2015-06-17 01:38 UTC
Labels: bug
