### ISSUE TITLE
hammer.js for single canvas game.

### ISSUE THREAD

**Issue by zzm2q** [hammerjs/hammer.js#739] opened 2014-12-15 01:45 UTC
Hi, guys
hammer.js is really cool, i use it in my game library.
and i want integrate it deeper, for example:

```javascript
var hammertime = new Hammer(myGameObjectNotAnCanvasElement, myOptions);
hammertime.on('pan', function(ev) {
    console.log(ev);
});
```

in the case of up, i have to fake a canvas element, is it the way going right? how many stuffs i have to fakes as canvas element containing a lot of properties and functions?

Thanks.

**Comment by sebakerckhof** [comment] 2015-01-23 07:11
If i understand your question correct, i think you just listen for hammer events on the canvas and then delegate them to your game objects. This might be as easy as checking an array of bounding boxes or make more complex datastructures and check depending on your needs and nb of objects.

**Comment by runspired** [comment] 2015-06-11 18:37
@sebakerckhof is correct, the objects painted on the canvas won't know about events, so you listen on the canvas element and delegate to structures based on coordinates.  How you look up structures in your game from those coordinates is an implementation that's up to you.

Closing as not a bug or feature request, just a discussion.

Future discussions for how to attain things like this are encouraged, but should not take place within issues.  A great place to ask would be on Slack, you can join the HammerJS Slack here: https://hammerjs-slackin.herokuapp.com/

**Closed by runspired** 2015-06-11 18:37 UTC
