### ISSUE TITLE
ReactJS Component

### ISSUE THREAD

**Issue by JedWatson** [hammerjs/hammer.js#713] opened 2014-11-14 13:29 UTC
Hi,

I just wanted to let you know I've been using hammerjs in a ReactJS mobile app and it works quite well, so I've packaged up the component I built to make it possible.

You can find it here: https://github.com/JedWatson/react-hammerjs

... or install `react-hammerjs` from npm or bower.

It's just got basic event support right now, not access to the full API, because that's all I needed, but if there's interest I'd be happy to extend it further and collaboration would be welcome.

Also happy to move it into the hammerjs org if you want it as an official plugin :)

**Comment by runspired** [comment] 2015-06-11 19:31
There are unofficial Ember and Angular plugins as well (I maintain one of the Ember ones).  We may talk about this in the future, but I think for now leaving these implementations to individuals with framework knowledge would be better.  @arschmitz 

Closing as not a bug/feature.

**Closed by runspired** 2015-06-11 19:31 UTC

**Comment by arschmitz** [comment] 2015-06-11 20:05
I agree i'm not inclined to add official integrations we don't already have we have enough work do on the core lib and the integrations we already have.
