### ISSUE TITLE
Hammer js events not firing when used in conjunction with velocity js

### ISSUE THREAD

**Issue by DarylThayil** [hammerjs/hammer.js#706] opened 2014-11-04 23:23 UTC
I am working with the velocity js animation library and I listen on the pan event and for every pan event do this 
```
$deck.velocity({
          translateX: distance + offset
        },{
          duration: 0,
        });
```
This works great on the desktop, great on IOS phonegap build , good on chrome mobile, but for some reason doesn't work on androids phonegap build

While debugging i found the issue ( or possibly a symptom of the issue ) is that Hammer events aren't being triggered quickly enough or often enough.  a gesture that would usually trigger 40-60 events in the browswer is triggering .... 5? in the android build.  When I comment out the above code for the animations, this problem goes away .... but then so does the desired functionality.

is this too intensive to run on every pan event? are there anythings you can think of in hammer to remedy this problem?

**Comment by runspired** [comment] 2015-06-11 19:02
@DarylThayil look into using Crosswalk for Android, but in general, yes, Android is hard to get great performance with and you likely needed to throttle the animation updates.

Closing as not a bug.  If you want to chat more about using Hammer on Android, you can find us on Slack: https://hammerjs-slackin.herokuapp.com/

**Closed by runspired** 2015-06-11 19:02 UTC
