### ISSUE TITLE
Hammer Element Disables Scrolling

### ISSUE THREAD

**Issue by johnstew** [hammerjs/hammer.js#638] opened 2014-08-07 13:54 UTC
I love hammer and have used it whenever I need to incorporate some mobile touch functionality. I love it and am still learning a lot with it. So I am using it across my entire site that I just built and I have certain elements that I have binded a tap event to and these elements take up the entire screen. I can scroll down to these elements just fine but when this element takes up the entire screen the scroll no longer works. It only happens on elements that have a Hammer event on them. I am sure this is something small I am missing or forgot to include as an option but was wondering if someone else has had this issue and could point me in the right direction. 

Thanks very much!

Note: This does not seem to be happening in version 2.0. However, in 1.0 it is.

**Comment by runspired** [comment] 2015-06-16 18:40
@johnstew The issue here is that vertical touch action setting delegates touches to your code instead of to default browser behavior.  This is intended spec-based behavior.  2.0 no longer specifies vertical touch-action properties by default in order to not break scroll unless that is the intention (in which case you manually configure it to do so).

Closing as V1 and since not a bug.

**Closed by runspired** 2015-06-16 18:40 UTC
