### ISSUE TITLE
How to implement two finger tap?

### ISSUE THREAD

**Issue by abhasg** [hammerjs/hammer.js#536] opened 2014-04-15 15:51 UTC
I am trying to implement two finger tap using this library on iOS Safari but don't have any success. As I understand if both the finger touches in span of little difference even 50ms it triggers pinch gesture.

With tap event I am checking event.gesture.touches.length === 2 it satisfy my requirement but its efficiency is very low.

Can you please help me to achieve this?

**Comment by arschmitz** [comment] 2015-06-10 03:43
Closing this as a support question not a bug

**Closed by arschmitz** 2015-06-10 03:43 UTC
