### ISSUE TITLE
where is the pull-to-refresh demo?

### ISSUE THREAD

**Issue by jackyon** [hammerjs/hammer.js#738] opened 2014-12-14 15:12 UTC
Hi,
seems it was removed? why? is it any perfect way using the pull-to-refresh feature with hammer js?

plz advise.

thx!

**Comment by arschmitz** [comment] 2015-06-07 20:00
Pull to refresh goes beyond just what hammer.js can do its actually not even really possible to due properly with JavaScript right now there is discussion around this currently in both the touch and pointer events groups at the W3C and what changes could enable this. Im going to close this as not a bug / Wont fit ( at least for now ).

**Closed by arschmitz** 2015-06-07 20:00 UTC
