### ISSUE TITLE
How do I recognize a swipe-without-lifting-finger gesture?

### ISSUE THREAD

**Issue by rstacruz** [hammerjs/hammer.js#623] opened 2014-07-27 15:29 UTC
I'd like to listen for a gesture that behaves like `swipe`, except that it wouldn't require you to lift your finger. This is present around iOS7 (for instance, it switches tabs in the notification center).

```js
mc = Hammer(el);
mc.on('flickleft', function () { switchToLeftTab(); });
mc.on('flickright', function () { switchToRightTab(); });
```

It's kinda like a pan left, but only triggers once. Is this possible with the default recognizers?

**Comment by runspired** [comment] 2015-08-07 20:40
Closing this as not a bug/issue but an implementation question.

**Closed by runspired** 2015-08-07 20:40 UTC
