### ISSUE TITLE
Pinch zoom not working after initializing Hammer on Chrome 37

### ISSUE THREAD

**Issue by Vaibhavjalan** [hammerjs/hammer.js#673] opened 2014-09-23 15:21 UTC
I was trying on Samsung S4 on the chrome browser. Just initializing the hammer code stops the pinch zoom functionality.

**Comment by arschmitz** [comment] 2015-06-11 20:16
Hammer allows you to customize the touch action http://hammerjs.github.io/touch-action/ closing as not a bug

**Closed by arschmitz** 2015-06-11 20:16 UTC
