### ISSUE TITLE
Disable pan while scrolling?

### ISSUE THREAD

**Issue by braco** [hammerjs/hammer.js#771] opened 2015-03-18 19:45 UTC
Seems to be a problem with mobile safari / ios webviews.

While scrolling vertically, if your finger drifts left/right, it will trigger pan on elements in the view.

What workarounds exist?

This is the only reference I could find: http://stackoverflow.com/questions/27193953/permit-horizontal-pan-events-only-if-the-gesture-is-not-already-scrolling-vertic

**Comment by jackyon** [comment] 2015-03-30 02:12
+1, i'm also looking for this.

**Comment by husseinsharif** [comment] 2015-05-07 22:33
+1  Working on a solution now.  I wonder why the "Lock Axis" property was removed in Hammer 2.x....

**Comment by husseinsharif** [comment] 2015-05-07 22:42
Here's the original open ticket: https://github.com/hammerjs/hammer.js/issues/633

**Comment by nitely** [comment] 2015-05-16 23:59
You can check the `ev.angle` on `panstart` and set a flag when the angle is pointing left or right, then do the pan action on `panmove` and reset the flag on `panend`.

Example:

```javascript
    // ...

    proto.swipestart = function(ev) {
            var angle = Math.abs(ev.angle);

            if (angle >= 90 && angle < 150)
                return;

            if (angle > 30 && angle < 90)
                return;

            this.moving = true;
            // ...
        };

        proto.swipemove = function(ev) {
            if (!this.moving)
                return;
            // ... change the marginLeft or translate to deltaX position
            // ...
        };

        proto.swipeend = function(ev) {
            if (!this.moving)
                return;

            this.moving = false;
            // ...
        };
```

**Comment by arschmitz** [comment] 2015-06-07 19:43
A work around for this is to just store the starting position. Then you can set a threshold for vertical offset from the start position, and check this in your pan handler if its more then your threshold just return.

I'm going to close this as not a bug. If this workaround does not work or if you think there is a bug here please comment and we will reopen

**Closed by arschmitz** 2015-06-07 19:43 UTC

**Comment by brandondurham** [comment] 2016-03-31 14:34
I’m using Hammer in a React component and was able to pull this off this way:

```javascript
const Hammertime = require('hammerjs');

// Grab a reference to Panel
const panel = this.refs.Panel;

// Create a Hammer manager
const mc = new Hammertime.Manager(panel);

// Create a recognizer
const Pan = new Hammertime.Pan();

// Add the recognizer
mc.add(Pan);

// Subscribe to events:

// If we detect a scroll before a panleft/panright, disable panning
mc.on('panstart', (event) => {
	if (event.additionalEvent === 'panup' || event.additionalEvent === 'pandown') {
		this.setState({isScrolling: true});
	}
});
// Reenable panning
mc.on('panend', () => this.setState({isScrolling: false}));
mc.on('pan', (event) => {
	if (!this.state.isScrolling) {
		// … do stuff
	}
});
```

**Comment by fredrikekelund** [comment] 2016-12-01 08:56
This solution is dead simple, but if all you want to do is to not activate a horizontal pan handler if the user is currently scrolling, and not scroll if the user is currently panning, then this worked well for me:

```js
var isScrolling = false;

var galleryHammer = new Hammer(element, {
    recognizers: [
        [Hammer.Pan, { direction: Hammer.DIRECTION_HORIZONTAL }]
    ]
});

// Making the event listener passive means we don't get any delays between
// the user scrolling and the browser having checked if it should prevent
// that event
window.addEventListener('scroll', function() {
    isScrolling = true;
}, { passive: true });

window.addEventListener('touchend', function() {
    isScrolling = false;
});

galleryHammer.on('pan', function(event) {
    if (isScrolling) {
        return;
    }

    // Normal logic...
});
```

**Comment by kevzlou7979** [comment] 2017-09-05 14:30
Any valid solution for this

**Comment by briancaffey** [comment] 2017-09-21 23:40
+1, i'm also looking for this.

**Comment by simeyla** [comment] 2018-08-28 08:32
Seems that there is a trick*, or rather a way *not* to do it. Fortunately I discovered this by accident before the vertical scrolling drove me too crazy - and it is for sure a far better experience when vertical scrolling is locked during panning.

* I'll assume we're talking about a horizontally scrolling div wider than the width of the screen with a few items than you position on pan event by setting `left` or `translate`.

Solution was quite simple: 

* The item you are positioning must not be `position: relative`
* Then the browser auto locks it for you when panning
* Sure there may be more to it than this and I don't fully understand why, but .....

I had the following (and I'm using Angular so `(pan)` is the auto-hooked up event on that element, and `#slider` lets me reference this div in code):

```
<div (pan)="pan($event)" #slider>
   <div class="slides-wrapper>
       <img />
       <img />
       <img />
    </div>
</div>
```

I originally had my `pan` handler on the `.slides-wrapper` div (which has position relative because I'm setting `left` to set the 'current slide' offset). It very oddly worked fine when dragging on the first image from side to side (scroll was locked), but when dragging left to right on the second image I could pan and then scroll vertically too no matter how careful I was. To be honest that part of it still doesn't make sense.

In my messing about I moved the `pan` handler up a level to the root of my 'image slider' and suddenly everything worked. 

To confirm I added `position: relative` to that root element and boom it broke again. I might add the panning still worked fine, what broke was that I could still scroll vertically.

So I'd recommend putting the pan handler (that sounds weird) on an outer node, with the element you move being a level underneath (which can be position: relative if you need).

Other than that I only used this hammer setting:

        pan: { direction: Hammer.DIRECTION_HORIZONTAL }

The browser completely automatically did the rest for me. No messing around with checking angles, or anything hacky at all. So now it feels exactly how it should.

Oh and if you *are* using Angular this is my complete config for my gesture config.

```
export class HammerPanHorizontalConfig extends HammerGestureConfig 
{
    overrides = <any>
    {
        'pinch': { enable: false },   
        'rotate': { enable: false },

        pan: { direction: Hammer.DIRECTION_HORIZONTAL },
        swipe: { direction: Hammer.DIRECTION_HORIZONTAL }
    }
}
```

Then provider this implementation :
```

  providers: [
    {
        provide: HAMMER_GESTURE_CONFIG,
        useClass: HammerPanHorizontalConfig
    }
  ]
```




(works for sure in iOS and Chrome devtools - not yet tested on real android device)

**Comment by stratboy** [comment] 2018-12-17 09:49
This worked for me (the code comes from a class, and this.hm is simply an Hammer instance):

``` js
this.hm.on('panleft', function(e){ // ...and same for panright
   if(e.pointerType == 'touch' && (Math.abs(e.deltaY) > Math.abs(e.deltaX))){ return false; }
   // do stuff
}
```
