### ISSUE TITLE
How to enable user scale for browser when use hammer?

### ISSUE THREAD

**Issue by devon** [hammerjs/hammer.js#851] opened 2015-09-14 09:59 UTC
```
<meta name="viewport" content="user-scalable=1,minimum-scale=1,maximum-scale=2,initial-scale=1">
```

There is a page with user-scalable = 1, and I need to enable the browser default scale behaviour. But it does not work when integrate hammer.js. I checked other issues but I cannot find a work solution.

**Comment by runspired** [comment] 2015-11-11 15:22
If you use a global hammer instance, or you write your own manager and use `pinch` or `rotate` recognizers, within the boundaries of the area the manager covers you will not be able to use the default browser scaling behavior.

Closing as not a bug, please ask questions on slack http://hammerjs-slackin.herokuapp.com/ or StackOverflow, thanks!

**Closed by runspired** 2015-11-11 15:22 UTC
