### ISSUE TITLE
Mouse events not working in Chrome

### ISSUE THREAD

**Issue by ohmycode** [hammerjs/hammer.js#1058] opened 2016-12-28 14:01 UTC
[Hammer js pinch Demo](https://hammerjs.github.io)

Neither pinch nor any other gesture with multiple finger input is being triggered while emulating  touches holding shift and dragging with the mouse. In Firefox and Safari it's still working.

**Comment by RopoMen** [comment] 2017-01-20 07:56
Relates https://github.com/hammerjs/touchemulator/issues/13

**Comment by MickL** [comment] 2018-08-14 09:49
Please close as duplicate of #13

**Closed** 2019-12-28 20:29 UTC
